name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[lint]
      - name: Run lints
        run: |
          isort src --check-only --diff
          black src --check
          flake8 src --max-line-length 88 --extend-ignore E203 --statistics
          mypy src
